# Generated by Django 3.2.3 on 2021-06-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avatar',
            name='avatar_svg',
            field=models.TextField(null=True),
        ),
    ]
